version: '3'

services:
  db:
    image: mysql:latest
    container_name: test-db
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h localhost -u root -proot']
      interval: 10s
      retries: 5
      start_period: 30s
